services:
  # Backend Service
  - type: web
    name: fake-news-detector-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python app.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
    healthCheckPath: /
